from __future__ import annotations

import argparse
import json
from pathlib import Path

from ks_solver import KSSolver
from paper_reproductions.linot2022_stab.data import DATA_DIR, DatasetConfig, ensure_dataset, make_onestep_pairs
from paper_reproductions.linot2022_stab.diagnostics import DiagnosticConfig, run_paper_diagnostics
from paper_reproductions.linot2022_stab.dynamics_extension import DynamicsConfig, run_dynamics_extension
from paper_reproductions.linot2022_stab.models import KSEContext, bundle_dict
from paper_reproductions.linot2022_stab.train import TrainingConfig, load_checkpoint, train_model


THIS_DIR = Path(__file__).resolve().parent
FIG_DIR = THIS_DIR / "figures"
PROGRESS_PATH = DATA_DIR / "run_reproduction_progress.json"
SUMMARY_PATH = DATA_DIR / "run_reproduction_summary.json"
RESULTS_MD = THIS_DIR / "RESULTS.md"


class RunTracker:
    def __init__(self, path: Path):
        self.path = path
        self.state = {"status": "running", "stages": []}
        self.flush()

    def mark(self, stage: str, **metrics):
        self.state["stages"].append({"stage": stage, "metrics": metrics})
        self.flush()

    def finish(self, **metrics):
        self.state["status"] = "completed"
        self.state["final"] = metrics
        self.flush()

    def fail(self, **metrics):
        self.state["status"] = "failed"
        self.state["final"] = metrics
        self.flush()

    def flush(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("w", encoding="utf-8") as f:
            json.dump(self.state, f, indent=2)


def stage_selected(args, stage: str) -> bool:
    return args.only is None or args.only == stage


def stage_forced(args, stage: str) -> bool:
    return args.force or stage in set(args.force_stage or [])


def stage_enabled(args, stage: str) -> bool:
    if stage == "data":
        return args.only in (None, "data")
    order = ["train", "diag", "dyn", "summary"]
    if args.only is None:
        return True
    if args.only not in order:
        return False
    return order.index(stage) <= order.index(args.only)


def checkpoint_path(model_name: str) -> Path:
    return DATA_DIR / f"model_{model_name}.pkl"


def history_path(model_name: str) -> Path:
    return DATA_DIR / f"history_{model_name}.json"


def progress_model_path(model_name: str) -> Path:
    return DATA_DIR / f"progress_{model_name}.json"


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def write_results_md(payload: dict) -> None:
    lines = [
        "# Linot 2022 Stabilized NODE Results",
        "",
        "This file is generated by `run_reproduction.py`.",
        "",
        "## Dataset",
        "",
        f"- Source: `{payload['dataset_meta'].get('source', 'unknown')}`",
        f"- Train shape: `{payload['dataset_meta'].get('train_shape')}`",
        f"- Test shape: `{payload['dataset_meta'].get('test_shape')}`",
        "",
        "## Training",
        "",
    ]
    for name, info in payload.get("training", {}).items():
        lines.append(f"- `{name}`: best epoch `{info['best_epoch']}`, best test loss `{info['best_test_loss']:.6f}`")
    lines.extend(["", "## Diagnostics", ""])
    if "diagnostics" in payload:
        diag = payload["diagnostics"]
        lines.append(f"- Spacetime steps: `{diag['spacetime_steps']}`")
        lines.append(f"- Joint PDF systems: `{', '.join(diag['joint_pdf_labels'])}`")
    else:
        lines.append("- Pending")
    lines.extend(["", "## Extension", ""])
    if "dynamics" in payload:
        for label, summary in payload["dynamics"].items():
            lines.append(
                f"- `{label}`: lambda_1=`{summary['lambda_1']:.5f}`, "
                f"n_pos=`{summary['n_positive']}`, "
                f"D_KY=`{summary['kaplan_yorke_dim']:.2f}`, "
                f"h_KS=`{summary['ks_entropy']:.5f}`"
            )
    else:
        lines.append("- Pending")
    RESULTS_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Linot 2022 KSE reproduction workflow")
    parser.add_argument("--force", action="store_true", help="Rerun every stage.")
    parser.add_argument("--only", choices=["data", "train", "diag", "dyn", "summary"], default=None)
    parser.add_argument(
        "--force-stage",
        choices=["data", "train", "diag", "dyn", "summary"],
        action="append",
        default=[],
        help="Force just one stage while leaving the others cached.",
    )
    parser.add_argument("--allow-generate", action="store_true", help="Generate data if caches are missing.")
    args = parser.parse_args()

    tracker = RunTracker(PROGRESS_PATH)
    context = KSEContext()
    solver = KSSolver(L=context.L, N=context.N, dt=context.tau)
    bundles = bundle_dict(context=context)

    try:
        train_states, test_states, dataset_meta = ensure_dataset(
            DatasetConfig(allow_generate=args.allow_generate)
        )
        tracker.mark("data_ready", train_shape=list(train_states.shape), test_shape=list(test_states.shape))
        if args.only == "data":
            write_json(SUMMARY_PATH, {"dataset_meta": dataset_meta})
            tracker.finish(summary_path=str(SUMMARY_PATH))
            return

        trained_models = {}
        train_requested = stage_enabled(args, "train") or stage_forced(args, "train")
        any_missing_checkpoints = any(not checkpoint_path(name).exists() for name in bundles)
        if train_requested:
            train_x, train_y = make_onestep_pairs(train_states)
            test_x, test_y = make_onestep_pairs(test_states)
            configs = {
                "nonlinear": TrainingConfig(
                    epochs=3000,
                    batch_size=256,
                    learning_rate=1.0e-3,
                    decay_boundaries=(0.5, 0.8),
                    decay_scales=(0.1, 0.1),
                    eval_every=10,
                    patience_epochs=100,
                    seed=0,
                ),
                "fixed_linear": TrainingConfig(
                    epochs=3000,
                    batch_size=256,
                    learning_rate=1.0e-3,
                    decay_boundaries=(0.5,),
                    decay_scales=(0.1,),
                    eval_every=10,
                    patience_epochs=100,
                    seed=1,
                ),
                "cnn": TrainingConfig(
                    epochs=3000,
                    batch_size=256,
                    learning_rate=1.0e-3,
                    decay_boundaries=(0.5,),
                    decay_scales=(0.1,),
                    eval_every=10,
                    patience_epochs=100,
                    seed=2,
                ),
            }
            for name, bundle in bundles.items():
                ckpt = checkpoint_path(name)
                if ckpt.exists() and not stage_forced(args, "train") and not args.force:
                    artifact = load_checkpoint(ckpt)
                else:
                    artifact = train_model(
                        bundle,
                        train_x,
                        train_y,
                        test_x,
                        test_y,
                        config=configs[name],
                        checkpoint_path=ckpt,
                        history_json_path=history_path(name),
                        progress_json_path=progress_model_path(name),
                    )
                artifact["bundle"] = bundle
                trained_models[name] = artifact
                tracker.mark(
                    f"trained_{name}",
                    best_epoch=artifact["best_epoch"],
                    best_test_loss=artifact["best_test_loss"],
                )
        elif any_missing_checkpoints:
            raise FileNotFoundError(
                "Training checkpoints are missing. Run with `--only train` or without `--only` first."
            )
        else:
            for name, bundle in bundles.items():
                artifact = load_checkpoint(checkpoint_path(name))
                artifact["bundle"] = bundle
                trained_models[name] = artifact

        summary_payload = {
            "dataset_meta": dataset_meta,
            "training": {
                bundles[name].display_name: {
                    "best_epoch": int(trained_models[name]["best_epoch"]),
                    "best_test_loss": float(trained_models[name]["best_test_loss"]),
                }
                for name in bundles
            },
        }

        if stage_selected(args, "diag") or stage_forced(args, "diag"):
            diag_summary = run_paper_diagnostics(
                solver=solver,
                context=context,
                test_states=test_states,
                trained_models=trained_models,
                figure_dir=FIG_DIR,
                data_dir=DATA_DIR,
                config=DiagnosticConfig(),
            )
            summary_payload["diagnostics"] = diag_summary
            tracker.mark("diagnostics_done", figure_dir=str(FIG_DIR))
        elif (DATA_DIR / "paper_diagnostics_summary.json").exists():
            summary_payload["diagnostics"] = json.loads((DATA_DIR / "paper_diagnostics_summary.json").read_text(encoding="utf-8"))

        if stage_selected(args, "dyn") or stage_forced(args, "dyn"):
            dynamics_summary = run_dynamics_extension(
                solver=solver,
                context=context,
                test_states=test_states,
                trained_models=trained_models,
                data_dir=DATA_DIR,
                figure_dir=FIG_DIR,
                config=DynamicsConfig(),
            )
            summary_payload["dynamics"] = dynamics_summary
            tracker.mark("dynamics_done", systems=list(dynamics_summary.keys()))
        elif (DATA_DIR / "dynamics_extension_summary.json").exists():
            dyn_payload = json.loads((DATA_DIR / "dynamics_extension_summary.json").read_text(encoding="utf-8"))
            summary_payload["dynamics"] = dyn_payload["systems"]

        write_json(SUMMARY_PATH, summary_payload)
        write_results_md(summary_payload)
        tracker.finish(summary_path=str(SUMMARY_PATH), results_md=str(RESULTS_MD))
    except Exception as exc:
        tracker.fail(error=str(exc))
        raise


if __name__ == "__main__":
    main()
